// Auto-generated by scripts/derive_mnist_expected_labels.py
// Source labels come from the labeled MNIST binary used by the C++ model.
expected_class[0] = 4'd7;
expected_class[1] = 4'd2;
expected_class[2] = 4'd1;
expected_class[3] = 4'd0;
expected_class[4] = 4'd4;
expected_class[5] = 4'd1;
expected_class[6] = 4'd4;
expected_class[7] = 4'd9;
expected_class[8] = 4'd5;
expected_class[9] = 4'd9;
