`timescale 1ns / 1ps

module reduced_vgg16_mnist_tiled #(
    parameter N = 8,
    parameter ES = 1,
    parameter IN_CH = 1,
    parameter IN_H = 28,
    parameter IN_W = 28,
    parameter C1 = 64,
    parameter C2 = 128,
    parameter C3 = 256,
    parameter C4 = 512,
    parameter FC1 = 256,
    parameter NUM_CLASSES = 10,
    parameter ROWS = 4,
    parameter COLS = 4,
    parameter CLASS_W = (NUM_CLASSES <= 2) ? 1 : $clog2(NUM_CLASSES),
    parameter H1 = IN_H,
    parameter W1 = IN_W,
    parameter H2 = ((H1 - 2) / 2) + 1,
    parameter W2 = ((W1 - 2) / 2) + 1,
    parameter H3 = ((H2 - 2) / 2) + 1,
    parameter W3 = ((W2 - 2) / 2) + 1,
    parameter H4 = ((H3 - 2) / 2) + 1,
    parameter W4 = ((W3 - 2) / 2) + 1,
    parameter H5 = ((H4 - 2) / 2) + 1,
    parameter W5 = ((W4 - 2) / 2) + 1
)(
    input  wire clk,
    input  wire reset,
    input  wire start,

    input  wire cfg_write_en,
    input  wire [3:0] cfg_layer,
    input  wire [1:0] cfg_mem,
    input  wire [31:0] cfg_addr,
    input  wire [N-1:0] cfg_data,

    output wire        param_req_valid,
    output wire [1:0]  param_req_kind,
    output wire [3:0]  param_req_layer,
    output wire [31:0] param_req_addr,
    input  wire        param_resp_valid,
    input  wire [N-1:0] param_resp_data,

    output wire        feature_rd_req_valid,
    output wire        feature_rd_bank,
    output wire [31:0] feature_rd_addr,
    input  wire        feature_rd_resp_valid,
    input  wire [N-1:0] feature_rd_resp_data,

    output wire        feature_wr_valid,
    output wire        feature_wr_bank,
    output wire [31:0] feature_wr_addr,
    output wire [N-1:0] feature_wr_data,

    input  wire [31:0] logit_read_addr,
    output wire [N-1:0] logit_read_data,

    output wire busy,
    output wire done,
    output wire [CLASS_W-1:0] class_out
);

    reduced_vgg16_mnist_tiled_core #(
        .N(N),
        .ES(ES),
        .USE_QUIRE(0),
        .IN_CH(IN_CH),
        .IN_H(IN_H),
        .IN_W(IN_W),
        .C1(C1),
        .C2(C2),
        .C3(C3),
        .C4(C4),
        .FC1(FC1),
        .NUM_CLASSES(NUM_CLASSES),
        .ROWS(ROWS),
        .COLS(COLS),
        .CLASS_W(CLASS_W),
        .H1(H1),
        .W1(W1),
        .H2(H2),
        .W2(W2),
        .H3(H3),
        .W3(W3),
        .H4(H4),
        .W4(W4),
        .H5(H5),
        .W5(W5)
    ) CORE (
        .clk(clk),
        .reset(reset),
        .start(start),
        .cfg_write_en(cfg_write_en),
        .cfg_layer(cfg_layer),
        .cfg_mem(cfg_mem),
        .cfg_addr(cfg_addr),
        .cfg_data(cfg_data),
        .param_req_valid(param_req_valid),
        .param_req_kind(param_req_kind),
        .param_req_layer(param_req_layer),
        .param_req_addr(param_req_addr),
        .param_resp_valid(param_resp_valid),
        .param_resp_data(param_resp_data),
        .feature_rd_req_valid(feature_rd_req_valid),
        .feature_rd_bank(feature_rd_bank),
        .feature_rd_addr(feature_rd_addr),
        .feature_rd_resp_valid(feature_rd_resp_valid),
        .feature_rd_resp_data(feature_rd_resp_data),
        .feature_wr_valid(feature_wr_valid),
        .feature_wr_bank(feature_wr_bank),
        .feature_wr_addr(feature_wr_addr),
        .feature_wr_data(feature_wr_data),
        .logit_read_addr(logit_read_addr),
        .logit_read_data(logit_read_data),
        .busy(busy),
        .done(done),
        .class_out(class_out)
    );

endmodule
