#!/usr/bin/env python3
"""
Derive expected labels for the Verilog MNIST memory-inference testbench.

The posit pixel .mem file contains only image pixels. Labels must come from a
labeled MNIST source, such as the custom mnist_test.bin used by
full_vgg16_mnist.cpp. This script reads both, verifies the image count/order as
far as possible, and writes a Verilog include containing expected_class[]
assignments.
"""

from __future__ import annotations

import argparse
import math
import struct
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MODEL_DIR = ROOT / "VGG16_MNIST_Epoch20"
if not DEFAULT_MODEL_DIR.exists():
    DEFAULT_MODEL_DIR = ROOT / "verilog" / "params"
DEFAULT_MEM = DEFAULT_MODEL_DIR / "mnist_pixels_posit8_1.mem"
DEFAULT_BIN = ROOT / "mnist_test.bin"
DEFAULT_OUT = ROOT / "tb" / "cnn" / "mnist_expected_labels.vh"
if not DEFAULT_OUT.parent.exists():
    DEFAULT_OUT = ROOT / "verilog" / "integrated" / "mnist_expected_labels.vh"


def posit8_1_to_float(bits: int) -> float:
    if bits == 0x00:
        return 0.0
    if bits == 0x80:
        return math.nan

    sign = -1.0 if (bits & 0x80) else 1.0
    ui = ((~bits + 1) & 0xFF) if sign < 0 else bits

    # Decode signless posit<8,1>.
    remaining = ui & 0x7F
    regime_sign = 1 if (remaining & 0x40) else 0
    run = 0
    mask = 0x40
    while mask and bool(remaining & mask) == bool(regime_sign):
        run += 1
        mask >>= 1

    k = run - 1 if regime_sign else -run

    # Skip terminating regime bit if present.
    if mask:
        mask >>= 1

    exponent = 0
    if mask:
        exponent = 1 if (remaining & mask) else 0
        mask >>= 1

    frac = 1.0
    place = 0.5
    while mask:
        if remaining & mask:
            frac += place
        place *= 0.5
        mask >>= 1

    useed = 2 ** (2**1)
    return sign * (useed**k) * (2**exponent) * frac


def read_posit_mem(path: Path, image_size: int, image_count: int) -> list[list[int]]:
    values: list[int] = []
    for line in path.read_text().splitlines():
        token = line.strip()
        if not token or token.startswith("//"):
            continue
        values.append(int(token, 16))

    expected = image_size * image_count
    if len(values) < expected:
        raise ValueError(f"{path} has {len(values)} values, expected at least {expected}")

    return [values[i * image_size : (i + 1) * image_size] for i in range(image_count)]


def read_custom_mnist_bin(path: Path, image_count: int) -> tuple[list[int], list[list[int]]]:
    data = path.read_bytes()
    if len(data) < 12:
        raise ValueError(f"{path} is too small to contain the custom MNIST header")

    nimages, rows, cols = struct.unpack_from("<III", data, 0)
    if rows != 28 or cols != 28:
        raise ValueError(f"{path} header rows/cols are {rows}x{cols}, expected 28x28")

    image_size = rows * cols
    offset = 12
    labels: list[int] = []
    images: list[list[int]] = []

    limit = min(image_count, nimages)
    for _ in range(limit):
        if offset + 1 + image_size > len(data):
            raise ValueError(f"{path} ended before {limit} labeled images could be read")
        labels.append(data[offset])
        offset += 1
        images.append(list(data[offset : offset + image_size]))
        offset += image_size

    return labels, images


def quantized_pixel_distance(
    mem_image: list[int], raw_image: list[int], pixel_scale: str
) -> float:
    # This is an ordering/preprocessing sanity check, not an encoder test.
    total = 0.0
    for pbits, raw in zip(mem_image, raw_image):
        reference = raw / 255.0 if pixel_scale == "normalized" else float(raw)
        total += abs(posit8_1_to_float(pbits) - reference)
    return total / len(mem_image)


def zero_mask_mismatch(mem_image: list[int], raw_image: list[int]) -> int:
    mismatches = 0
    for pbits, raw in zip(mem_image, raw_image):
        if (pbits == 0) != (raw == 0):
            mismatches += 1
    return mismatches


def write_verilog_include(path: Path, labels: list[int]) -> None:
    lines = [
        "// Auto-generated by scripts/derive_mnist_expected_labels.py",
        "// Source labels come from the labeled MNIST binary used by the C++ model.",
    ]
    for idx, label in enumerate(labels):
        lines.append(f"expected_class[{idx}] = 4'd{label};")
    path.write_text("\n".join(lines) + "\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--mem", type=Path, default=DEFAULT_MEM)
    parser.add_argument("--mnist-bin", type=Path, default=DEFAULT_BIN)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--images", type=int, default=10)
    parser.add_argument(
        "--pixel-scale",
        choices=("raw", "normalized"),
        default="raw",
        help="preprocessing used when the Posit pixel memory was exported",
    )
    args = parser.parse_args()

    image_size = 28 * 28
    mem_images = read_posit_mem(args.mem, image_size, args.images)
    labels, raw_images = read_custom_mnist_bin(args.mnist_bin, args.images)

    if len(labels) != args.images:
        raise ValueError(f"Only found {len(labels)} labels, expected {args.images}")

    distances = [
        quantized_pixel_distance(mem_images[i], raw_images[i], args.pixel_scale)
        for i in range(args.images)
    ]
    zero_mismatches = [
        zero_mask_mismatch(mem_images[i], raw_images[i])
        for i in range(args.images)
    ]

    args.out.parent.mkdir(parents=True, exist_ok=True)
    write_verilog_include(args.out, labels)

    print(f"Labels: {labels}")
    print(f"Wrote: {args.out}")
    print("Mean abs pixel differences between posit mem and labeled binary:")
    for i, dist in enumerate(distances):
        print(
            f"  image {i}: label={labels[i]} "
            f"mean_abs_diff={dist:.6f} zero_mask_mismatches={zero_mismatches[i]}"
        )
    print(f"Overall mean_abs_diff={sum(distances) / len(distances):.6f}")
    print(f"Total zero_mask_mismatches={sum(zero_mismatches)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
